language: ruby
rvm:
- 2.4.2
install:
- bundle install
script: jekyll build && htmlproofer ./_site
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
